### ISSUE TITLE
Hvordan Finner Jeg Midtpunkten?

### ISSUE THREAD

**Issue by Miserlou** [oysteinmyrmo/bezier#2]
Hei Øystein!

Unnskyld, jeg vet dette er et gammelt prosjekt, man hvordan finner jeg midpointten av kurven? 

If this functionality is not yet available, I'll figure it out and send a PR!

(Please excuse my Norsk, I am still learning!)
Rich

**Comment by oysteinmyrmo** [comment]
Hei, Rich!

By center point, do you mean center point along the curve itself? If so, you can do as in the README: `someBezier.valueAt(0.5)`, which returns a `Bezier::Point` type. Will this suffice?

---
In Norwegian:

Med midtpunkt, mener du punktet midt på kurven, langs kurven? Hvis ja, kan du gjøre som i README-en: `someBezier.valueAt(0.5)`, som returnerer en `Bezier::Point` type. Er dette ok for deg?

**Comment by Miserlou** [comment]
Takk for the replies! I'm going to keep going in English just to be more clear:

I am interested in finding the midpoint of the curve itself, not the value of the curve at t=.5. So, choose a point on the line, then the two halves will have the same length (within some small margin of error).

This requires a search algorithm, as illustrated here: https://github.com/Pomax/bezierjs/issues/69#issuecomment-275002732

I see there is an 'epsillon' in the bezier.h code, but I don't think it's being used for the same purpose.

Does this make sense?

Cheers 
Rich

**Comment by oysteinmyrmo** [comment]
Right, I see now what you mean. The `epsilon` in `bezier.h` is used for various fuzzy compares and for calculating extreme values with Newton Rhapson, so it is something else. There is currently no way to do what you need, and it is a bit involved as you can see from Pomax's excellent Bezier Primer at https://pomax.github.io/bezierinfo/#arclength

The problem is thus twofold: 1) we need a function to compute arc lengths, and 2) we need to find the center point, for example like Pomax suggests in the comment you refer to. Now, while this looks really fun to implement, I am fairly pressed on time these days. It is hard to estimate the time it will take to implement this in my evenings. Maybe I can find the time within May, maybe not.

If you need this very quickly I suggest creating a fork and look into it. I will of course accept a pull request if it looks ok. There are no strict code guidelines, but I expect things to look like the rest of the file (4 spaces for indentation, curly braces below each other, etc.). Let me know if you start digging into it.

**Comment by Miserlou** [comment]
Hey, was just wondering if you'd gotten another chance to think about this!

To be honest, I tried twice and got so tangled up in the mathematics that I didn't come up with a satisfactory result :(..

**Comment by oysteinmyrmo** [comment]
I have had it in the back of my mind, but I haven't found the time to look into it. I am also working on an app in my spare time and I am about to release it so that takes most of my spare time these days. So I am sorry to say that I still do not know when I will find the time to do it.

I did a small recap for my own sake. This is how I would outline the approach if I were to do it:

1. Implement splitting of bezier curves as described in https://pomax.github.io/bezierinfo/#splitting. You would then need to implement Casteljau's algorithm: https://pomax.github.io/bezierinfo/#decasteljau. This part should not be too complicated with some thinking: Take a `Bezier` as argument to a function, calculate the tangent at the desired `t` (already implemented, see the `Bezier::tangentAt()` function) and interpolate on the lines between the control points on the bezier curve. The animation in the primer for Casteljau's algorithm is very nice if you spend some time staring at it! Going through it on paper would likely prove fruitful as well as is also suggested in the primer.
2. Brute force the arc length calculation! Create a function that divides the bezier curve into `N` segments. For example 10 segments and calculate the length of each segment with Pythagoras, using the `Bezier:: valueAt(float t)` function. Find an `N` that satisfies your requirement for accuracy. This will be fairly fast as long as you don't use extreme amounts of segments. See https://pomax.github.io/bezierinfo/#arclengthapprox
3. Now you could use Pomax's pseudo code to calculate the center point: https://github.com/Pomax/bezierjs/issues/69#issuecomment-275002732

This should be more than fast enough unless you are about to do this all the time. (Which would be kinda weird :) )

Maybe this recap could help you out?

**Comment by Miserlou** [comment]
Thank you for your swift and detailed reply! This will be very helpful for trying this implementation.

What's the new app? :)

**Comment by oysteinmyrmo** [comment]
Let me know how it goes. I think I can find some time to look at it this weekend in any case.

The app is a recipe/shopping list app for my girlfriend's food blog, only available in Scandinavia (it's in Norwegian). Almost done, but Apple delays me! :-)

**Comment by oysteinmyrmo** [comment]
By the way, I ran the tests in Windows and became sad by the number of warnings. XCode didn't give any warnings for the last 2-year old commit, but Visual Studio didn't (correctly) like it. I fixed and pushed all of them and there are still no warnings showing in Xcode. Most changes are double --> float. Only a few of the test values needed to be fixed, so the precision is stil good enough IMO.

**Comment by oysteinmyrmo** [comment]
I decided to implement it as it was not too much work after doing some thinking. The implementation is very similar to what is done in the earler mentioned sources. These implementation may be considered as brute force and may not be entirely optimal, but I would be surprised if you run into performance issues with this.

Here is a sample as per the README:

```
Bezier::Bezier<3> cubicBezier({ {120, 160}, {35, 200}, {220, 260}, {220, 40} });
float tAtMidPoint = cubicBezier.archMidPoint();            // 0.70718
Bezier::Point midPoint = cubicBezier.valueAt(tAtMidPoint); // (183.8, 168.8)
```

Will this suffice for your use case? It should be possible to add support for finding the `t` for arbitrary locations on the arch length, not just the midpoint (e.g. `0.333` or similar).

Implementation references:

https://github.com/oysteinmyrmo/bezier/blob/f737bb22200836ad007744fc21456eec75b178b6/include/bezier.h#L759
https://github.com/oysteinmyrmo/bezier/blob/f737bb22200836ad007744fc21456eec75b178b6/include/bezier.h#L785
https://github.com/oysteinmyrmo/bezier/blob/f737bb22200836ad007744fc21456eec75b178b6/include/bezier.h#L820

Tests are at https://github.com/oysteinmyrmo/bezier/blob/f737bb22200836ad007744fc21456eec75b178b6/tests/basic-tests.cpp

**Comment by Miserlou** [comment]
Amazing, I love you!!! I think this will suffice, since my application only updates the curve when values change in the UI. You rock so much! Thank you thank you!

BTW - what's your girlfriend's food blog? I have a Norsk girlfriend who loves food blogs..

**Comment by oysteinmyrmo** [comment]
Glad to be of help! :-)

This is her blog: https://www.miasmat.no/

There is already an Android app, but I am working on the iOS app now, writing the business logic in C++ and porting that back to the (Java only) Android app.
