### ISSUE TITLE
Call to non-constexpr function error when Bezier::Bezier<VARIABLE> initialization

### ISSUE THREAD

**Issue by onatkeser** [oysteinmyrmo/bezier#8]
I would like to calculate Bezier in the runtime as: 
Bezier::Bezier<path.rows()> cubicBezier({ <some points> }); where path.rows() is the number of 2D point. However, it does not allow me to do so. Could you help about that issue? Can't we assign this in the runtime?
Thanks in advance

**Comment by oysteinmyrmo** [comment]
What is your error message? Is `path.rows()` a constant compile time expression?

**Comment by onatkeser** [comment]
error: call to non-constexpr function ‘Eigen::Index Eigen::PlainObjectBase<Derived>::rows() const [with Derived =Eigen::Matrix<float, -1, 5>; Eigen::Index = long int]’                                                                                                 
         Bezier::Bezier<path.rows()> cubicBezier({ {0, 0} });

**Comment by onatkeser** [comment]
path.rows() is not a constant. My aim is basically able to decide Bezier::Bezier<VARIABLE> in runtime

**Comment by oysteinmyrmo** [comment]
It is not possible to pass a runtime variable to as a template argument. It has to be a compile time constant expression. See for example https://en.cppreference.com/w/cpp/language/templates

I suppose you could create some templates or functions of your own to make it work:

```
switch(path.rows())
{
    case 2:
        // Call a function that explicitly uses Bezier::Bezier<2>.
    case 3:
        // Call a function that explicitly uses Bezier::Bezier<3>.
    default:
        break;
}
```

Although this could get messy very quickly.

I will close this for now since I consider this to be out of the library's scope. See for example [this](https://stackoverflow.com/questions/68839163/is-it-impossible-to-pass-a-run-time-integer-as-a-template-argument) StackOverflow question which is the same as you are trying to do.
